#!/usr/bin/env python3

from __future__ import absolute_import, division, print_function

import logging
import os
import sys


sys.path.append(
    os.path.join(os.path.dirname(os.path.dirname(sys.argv[0])), 'lib'))

from jsa_proc_transient.dr import create_reference_catalog

logging.basicConfig(level=logging.DEBUG)

for source in [
        'IC348',
        'NGC1333',
        'NGC2024',
        'NGC2071',
        'OMC23',
        'OPH_CORE',
        'SERPENS_MAIN',
        'SERPENS_SOUTH',
        ]:
    for filter_ in ['850', '450']:
        create_reference_catalog(source, filter_)
