#!/usr/bin/env python3

from __future__ import absolute_import, division, print_function

import logging
import os
import shutil
import sys

# Add relative library directory to path.
sys.path.append(
    os.path.join(os.path.dirname(os.path.dirname(sys.argv[0])), 'lib'))

from jsa_proc.custom.run import CustomJobRun
from jsa_proc_transient.dr import transient_analysis_all


program_name = os.path.basename(sys.argv[0])
logger = logging.getLogger(program_name)


class TransientRun(CustomJobRun):
    def run_processing(self, inputs, transdir, id_='unknown'):
        """
        Function to launch data processing.

        :param inputs: list of input file names
        :param transdir: target output directory
        :param id: job identifier
        """

        outputs = transient_analysis_all(inputs)

        for filename in outputs:
            if filename.endswith('.sdf'):
                logger.info('Storing SDF file "%s"', filename)
                shutil.copy(filename, transdir)

            elif filename.endswith('.FIT'):
                filename_edited = filename[:-4] + '.fits'
                logger.info('Storing FITS file "%s" as "%s"',
                            filename, filename_edited)
                shutil.copyfile(
                    filename, os.path.join(transdir, filename_edited))

            else:
                raise Exception('Unexpected output file "{}"'.format(filename))


if __name__ == '__main__':
    TransientRun(program_name=program_name).run()
